# Generated by Django 3.1.6 on 2021-02-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0002_audiofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofiles',
            name='user',
        ),
    ]
