# Generated by Django 3.1.6 on 2021-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0007_auto_20210316_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofiles',
            name='audio',
            field=models.FileField(upload_to='media/'),
        ),
    ]
