# Generated by Django 3.1.6 on 2021-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0009_auto_20210316_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofiles',
            name='audio',
            field=models.FileField(upload_to='media/'),
        ),
    ]
