# Generated by Django 3.1.6 on 2021-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0011_transcript_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofiles',
            name='username',
        ),
        migrations.AddField(
            model_name='audiofiles',
            name='audio_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
