# Generated by Django 3.1.6 on 2021-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0012_auto_20210317_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript_summary',
            name='transcript',
            field=models.TextField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='transcript_summary',
            name='summary',
            field=models.TextField(default=0, max_length=5000),
        ),
    ]
