# Generated by Django 3.1.6 on 2021-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imom', '0013_auto_20210318_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript_summary',
            name='summary',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='transcript_summary',
            name='transcript',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
