# Generated by Django 3.1.8 on 2021-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofiles',
            name='meeting_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
